### ISSUE TITLE
TQMa8Xx.0100 with MBA8Xx-P1 RK.0102 zeus boot problem

### ISSUE THREAD

**Issue by beratiks** [tq-systems/bsp-work#3]
I tried to build your last release zeus branch. I built but when I try to boot my device (TQMa8Xx.0100 with MBA8Xx-P1 RK.0102) not seems anything from terminal. I did everything exactly what you say this page : https://support.tq-group.com/en/arm/tqma8xx/linux/yocto/quickstart_yocto​

Why happened this problem? Am I miss something or zeus has problems?

**Comment by tq-niebelm** [comment]
Sorry for the late reply, I was on holiday. Please note, that the zeus Branch currently under development is focused on hardware revision 020x using CPU with C0 die stepping.
TQMa8Xx / MBa8Xx REV.010x are not compatible. See README.md.

**Comment by beratiks** [comment]
Thanks for your reply.
