### ISSUE TITLE
Having Error "ERROR: Nothing PROVIDES 'virtual/kernel'"

### ISSUE THREAD

**Issue by rass92** [tq-systems/bsp-work#5]
Dear Community,

I have an MBLS1028A-IND and I am doing all the steps stated in the following page

https://support.tq-group.com/en/layerscape/tqmls1028a/mbls1028a-ind/linux/yocto/quickstart_yocto

When I do that I recieve the following

ERROR: Nothing PROVIDES 'virtual/kernel' (but /home/tqmls1028a/Yocto/ci-meta-tq/sources/meta-dumpling/recipes-images/images/tq-image-generic.bb DEPENDS on or otherwise requires it)
linux-imx-tq PROVIDES virtual/kernel but was skipped: PREFERRED_PROVIDER_virtual/kernel set to linux-rt-lsdk-tq, not linux-imx-tq
linux-rt-tq PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-rt-tq PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-ti-tq PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-ti-tq PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-tq PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-tq PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-tq PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-tqmt PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-qoriq PROVIDES virtual/kernel but was skipped: PREFERRED_PROVIDER_virtual/kernel set to linux-rt-lsdk-tq, not linux-qoriq
linux-fslc-imx PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-imx PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-fslc-lts-4.19 PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-qoriq PROVIDES virtual/kernel but was skipped: PREFERRED_PROVIDER_virtual/kernel set to linux-rt-lsdk-tq, not linux-qoriq
linux-fslc-imx-rt PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-qoriq-rt PROVIDES virtual/kernel but was skipped: PREFERRED_PROVIDER_virtual/kernel set to linux-rt-lsdk-tq, not linux-qoriq-rt
linux-fslc PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-yocto-tiny PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-yocto-dev PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-yocto PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-yocto-rt PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-yocto PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-yocto-rt PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-yocto-tiny PROVIDES virtual/kernel but was skipped: incompatible with machine tqmls1028a-mbls1028a-ind (not in COMPATIBLE_MACHINE)
linux-dummy PROVIDES virtual/kernel but was skipped: PREFERRED_PROVIDER_virtual/kernel set to linux-rt-lsdk-tq, not linux-dummy
ERROR: Required build target 'tq-image-generic' has no buildable providers.
Missing or unbuildable dependency chain was: ['tq-image-generic', 'virtual/kernel']

this is my conf/local.conf file

roberto@roberto-Latitude-E4310:/home/tqmls1028a/Yocto/ci-meta-tq/tqmls1028a_build$ cat conf/local.conf
MACHINE ??= "tqma57xx-ecc-mba57xx"
DISTRO ?= "poky"
PACKAGE_CLASSES ?= "package_rpm"
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
USER_CLASSES ?= "buildstats image-mklibs image-prelink"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    ABORT,${TMPDIR},100M,1K \
    ABORT,${DL_DIR},100M,1K \
    ABORT,${SSTATE_DIR},100M,1K \
    ABORT,/tmp,10M,1K"
PACKAGECONFIG_append_pn-qemu-system-native = " sdl"
CONF_VERSION = "1"
ACCEPT_FSL_EULA = "1"
MACHINE = "tqmls1028a-mbls1028a-ind"
PREFERRED_PROVIDER_virtual/kernel_tqmls1028a = "linux-rt-lsdk-tq"

Any hint of what could be the issue?

Thank in advance

**Comment by tq-gregorHerburger** [comment]
Hi rass92,

sorry for the late response. 

Looks like your meta-tq is not on the right commit and is missing the linux-rt-lsdk-tq recipe. Maybe the submodule update in step 3 went wrong. 

If you are using `zeus.TQMLS1028A.BSP.SW.0104` of ci-meta-tq as the instruction suggests your meta-tq should be on commit dbf19859ddef4b70719b5844bdfa438075ae167e. 

Can you check if meta-tq is on that commit and if there is a recipes-kernel/linux/linux-rt-lsdk-tq_5.4.bb in your meta-tq.

**Comment by tq-niebelm** [comment]
@gregorHerburger please check, if this can be closed.

**Comment by tq-gregorHerburger** [comment]
Closed due to no response.
