### ISSUE TITLE
can't activate openssh in scarthgap

### ISSUE THREAD

**Issue by pfostenberg** [tq-systems/bsp-work#8]
Hi

we are change from an old version to scarthgap. But I can't activated openssh in the standard scathgap distro.

first try with change this file 
scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/tqma8mpxl_build/conf/local.conf
adding
IMAGE_INSTALL:append = " openssh "

causes an error like this.

ERROR: tq-image-small-debug-1.0-r0 do_rootfs: Could not invoke dnf. Command '/home/mza/workspace/scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux/tq-image-small-debug/1.0/recipe-sysroot-native/usr/bin/dnf -v --rpmverbosity=info -y -c /home/mza/workspace/scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux/tq-image-small-debug/1.0/rootfs/etc/dnf/dnf.conf --setopt=reposdir=/home/mza/workspace/scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux/tq-image-small-debug/1.0/rootfs/etc/yum.repos.d --installroot=/home/mza/workspace/scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux/tq-image-small-debug/1.0/rootfs --setopt=logdir=/home/mza/workspace/scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux/tq-image-small-debug/1.0/temp --repofrompath=oe-repo,/home/mza/workspace/scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux/tq-image-small-debug/1.0/oe-rootfs-repo --nogpgcheck install kernel-devicetree kernel-image openssh openssh-sftp openssh-sftp-server packagegroup-audio packagegroup-base packagegroup-can packagegroup-core-boot packagegroup-core-ssh-dropbear packagegroup-fsutils packagegroup-hwutils-base packagegroup-netutils packagegroup-npu packagegroup-systemd packagegroup-sysutils packagegroup-wifi run-postinsts locale-base-de-de locale-base-en-us' returned 1:
DNF version: 4.19.0
cachedir: /home/mza/workspace/scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux/tq-image-small-debug/1.0/rootfs/var/cache/dnf
Added oe-repo repo from /home/mza/workspace/scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux/tq-image-small-debug/1.0/oe-rootfs-repo
User-Agent: falling back to 'libdnf': could not detect OS or basearch
repo: using cache for: oe-repo
oe-repo: using metadata from Mon 02 Dec 2024 11:24:57 AM UTC.
Last metadata expiration check: 0:00:01 ago on Mon 02 Dec 2024 11:39:33 AM UTC.
--> Starting dependency resolution
--> Finished dependency resolution
**Error: 
 Problem: package packagegroup-core-ssh-dropbear-1.0-r0.noarch from oe-repo requires dropbear, but none of the providers can be installed
  - package dropbear-2022.83-r0.cortexa53_crypto from oe-repo conflicts with openssh provided by openssh-9.6p1-r0.cortexa53_crypto from oe-repo
  - package openssh-9.6p1-r0.cortexa53_crypto from oe-repo conflicts with dropbear provided by dropbear-2022.83-r0.cortexa53_crypto from oe-repo
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages**)

ERROR: Logfile of failure stored in: /home/mza/workspace/scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux/tq-image-small-debug/1.0/temp/log.do_rootfs.3200469
ERROR: Task (/home/mza/workspace/scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/sources/meta-tq/meta-dumpling/recipes-images/images/tq-image-small-debug.bb:do_rootfs) failed with exit code '1'

found this reference to dropbear:

mza@ybm:~/workspace$ find . -type f -name "*.bb*" -exec grep -H 'TASK_BASIC_SSHDAEMON' {} \;
./scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/sources/meta-openembedded/meta-oe/recipes-core/packagegroups/packagegroup-basic.bb:# Set TASK_BASIC_SSHDAEMON = "openssh-sshd openssh-sftp openssh-sftp-server" in your DISTRO config to get openssh(d)
./scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/sources/meta-openembedded/meta-oe/recipes-core/packagegroups/packagegroup-basic.bb:TASK_BASIC_SSHDAEMON ?= "dropbear openssh-sftp openssh-sftp-server"
./scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/sources/meta-openembedded/meta-oe/recipes-core/packagegroups/packagegroup-basic.bb:    ${TASK_BASIC_SSHDAEMON} \

Tried with adding:
TASK_BASIC_SSHDAEMON = "openssh-sshd openssh-sftp openssh-sftp-server"  

bitbake tq-image-small-debug
success..

but no /etc/ssh in rootfs?

the adding to local.conf.
 IMAGE_INSTALL:append = " openssh "
same error as above.

Any idears? or does openssh does not work with scathgap? 

should be like this?
https://support.tq-group.com/en/arm/tqma8xxs/linux/yocto/how_to/target

**Comment by tq-niebelm** [comment]
Hi,

tq-image-small[-debug] and distro definition `spaetzle` are there to demonstrate how to create a small system fitting in QSPI nor. Hence instead of openssh dropbear will be used.

You can make use of standard  poky or base on dumpling[-wayland][-flavour]

See README in BSP and in meta-tq for details

**Comment by pfostenberg** [comment]
I tried with kirstone...  but the same as with scarthgap.
As recommended Spaetzle...

as soon as I add 
IMAGE_INSTALL:append = " openssh"
in local.conf...


Build Configuration:
BB_VERSION           = "2.0.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-tq-linux-musl"
MACHINE              = "tqma8mpxl-mba8mpxl"
**DISTRO               = "spaetzle-nxp"**
DISTRO_VERSION       = "4.0.20"
TUNE_FEATURES        = "aarch64 armv8a crc cortexa53 crypto"
TARGET_FPU           = ""
meta                 
meta-poky            = "HEAD:6bd3969d32730538608e680653e032e66958fe84"
meta-oe              
meta-python          
meta-multimedia      = "HEAD:4052c97dc83d0c88fc277d6fc1815e0699020daa"
meta-freescale       = "HEAD:4c81b4161b99698b03332842b588dd8235ac47e4"
meta-freescale-ml    = "HEAD:320468fe4d95f06dc1ee1cf165a7acd25a682624"
meta-qt5             = "HEAD:eb828418264a49b8d00035cb3d7b12fcea3be801"
meta-tq              
meta-dumpling        = "HEAD:8ea9314df8a11eabb38946f064c83b8e8bb1990c"
meta-networking      = "HEAD:4052c97dc83d0c88fc277d6fc1815e0699020daa"
meta-spb228-pcie     
meta-spb228-usb      
meta-ivantoconnect   = "kirkstone:2415657f42a509a1abee77abc3f44b6b0d9176c5"

Initialising tasks: 100% |###############################################################################################################################################################################################################| Time: 0:00:05
Sstate summary: Wanted 115 Local 107 Mirrors 0 Missed 8 Current 1166 (93% match, 99% complete)
Removing 2 stale sstate objects for arch tqma8mpxl_mba8mpxl: 100% |######################################################################################################################################################################| Time: 0:00:00
NOTE: Executing Tasks
ERROR: tq-image-small-debug-1.0-r0 do_rootfs: Could not invoke dnf. Command '/home/mza/workspace/kirkstone.TQ.ARM.BSP.0018/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux-musl/tq-image-small-debug/1.0-r0/recipe-sysroot-native/usr/bin/dnf -v --rpmverbosity=info -y -c /home/mza/workspace/kirkstone.TQ.ARM.BSP.0018/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux-musl/tq-image-small-debug/1.0-r0/rootfs/etc/dnf/dnf.conf --setopt=reposdir=/home/mza/workspace/kirkstone.TQ.ARM.BSP.0018/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux-musl/tq-image-small-debug/1.0-r0/rootfs/etc/yum.repos.d --installroot=/home/mza/workspace/kirkstone.TQ.ARM.BSP.0018/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux-musl/tq-image-small-debug/1.0-r0/rootfs --setopt=logdir=/home/mza/workspace/kirkstone.TQ.ARM.BSP.0018/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux-musl/tq-image-small-debug/1.0-r0/temp --repofrompath=oe-repo,/home/mza/workspace/kirkstone.TQ.ARM.BSP.0018/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux-musl/tq-image-small-debug/1.0-r0/oe-rootfs-repo --nogpgcheck install kernel-devicetree kernel-image myhello openssh packagegroup-base packagegroup-can packagegroup-core-boot packagegroup-core-ssh-dropbear packagegroup-fsutils packagegroup-hwutils-base packagegroup-netutils packagegroup-sysutils run-postinsts' returned 1:
DNF version: 4.11.1
cachedir: /home/mza/workspace/kirkstone.TQ.ARM.BSP.0018/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux-musl/tq-image-small-debug/1.0-r0/rootfs/var/cache/dnf
Added oe-repo repo from /home/mza/workspace/kirkstone.TQ.ARM.BSP.0018/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux-musl/tq-image-small-debug/1.0-r0/oe-rootfs-repo
User-Agent: falling back to 'libdnf': could not detect OS or basearch
repo: using cache for: oe-repo
oe-repo: using metadata from Mon 02 Dec 2024 06:03:11 PM UTC.
Last metadata expiration check: 0:00:01 ago on Mon 02 Dec 2024 06:03:11 PM UTC.
--> Starting dependency resolution
--> Finished dependency resolution
Error: 
 Problem: package packagegroup-core-ssh-dropbear-1.0-r1.noarch requires dropbear, but none of the providers can be installed
  - package dropbear-2020.81-r0.cortexa53_crypto conflicts with openssh provided by openssh-8.9p1-r0.cortexa53_crypto
  - package openssh-8.9p1-r0.cortexa53_crypto conflicts with dropbear provided by dropbear-2020.81-r0.cortexa53_crypto
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)

ERROR: Logfile of failure stored in: /home/mza/workspace/kirkstone.TQ.ARM.BSP.0018/ci-meta-tq/tqma8mpxl_build/tmp/work/tqma8mpxl_mba8mpxl-tq-linux-musl/tq-image-small-debug/1.0-r0/temp/log.do_rootfs.102418
ERROR: Task (/home/mza/workspace/kirkstone.TQ.ARM.BSP.0018/ci-meta-tq/sources/meta-tq/meta-dumpling/recipes-images/images/tq-image-small-debug.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3143 tasks of which 3129 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/mza/workspace/kirkstone.TQ.ARM.BSP.0018/ci-meta-tq/sources/meta-tq/meta-dumpling/recipes-images/images/tq-image-small-debug.bb:do_rootfs
Summary: There were 2 WARNING messages.
Summary: There was 1 ERROR message, returning a non-zero exit code.

With out.... rootfs is created but no directory /etc/ssh/ ... 

will try with scarthgap tomorrow.

**Comment by tq-niebelm** [comment]
Please have a look at https://github.com/tq-systems/meta-tq/blob/257b8c0b4b6df3bb27fb69bd2312dd254c73fed3/meta-dumpling/recipes-images/images/tq-image-small.bb#L10

`tq-image-small[-debug]` is intended to use as example with a tiny distro and therefore __enforces__ dropbear.

`tq-image-generic[-debug] / `tq-image-weston[-debug]` / `tq-image- qt5[-debug]` are example images with `openssh` intended to be used with more feature rich distros.

**Comment by pfostenberg** [comment]
OK then I tried a clean checkout as described her.
https://support.tq-group.com/en/arm/tqma8mpxl/linux/yocto/quickstart_yocto
only change ( for the openssh ) 
export DISTRO=spaetzle-nxp

then bitbake tq-image-small -> success. but no openssh as described above. ( as expected)

when I try 
 **bitbake tq-image-generic-debug**
Loading cache: 100% |######################################################################################################################################################################################################################| Time: 0:00:01
Loaded 4782 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES '${VIRTUAL-RUNTIME_base-utils-lscpu}' (but /home/mza/workspace/scarthgap.TQ.ARM.BSP.0001/ci-meta-tq/sources/meta-tq/meta-dumpling/recipes-images/packagegroups/packagegroup-testutils.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${VIRTUAL-RUNTIME_base-utils-lscpu}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${VIRTUAL-RUNTIME_base-utils-lscpu}']
NOTE: Runtime target 'packagegroup-testutils' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-testutils', '${VIRTUAL-RUNTIME_base-utils-lscpu}']
ERROR: Required build target 'tq-image-generic-debug' has no buildable providers.
Missing or unbuildable dependency chain was: ['tq-image-generic-debug', 'packagegroup-testutils', '${VIRTUAL-RUNTIME_base-utils-lscpu}']

also with 
bitbake tq-image-weston
Loading cache: 100% |######################################################################################################################################################################################################################| Time: 0:00:01
Loaded 4782 entries from dependency cache.
ERROR: Nothing PROVIDES 'tq-image-weston'
tq-image-weston was skipped: Recipe will be skipped because: not buildable with spaetzle: use tq-image-small

Summary: There was 1 ERROR message, returning a non-zero exit code.

**Comment by tq-schiffern** [comment]
As noted by @tq-niebelm, do *not* use spaetzle if you want OpenSSH. Use dumpling or poky.

**Comment by tq-niebelm** [comment]
Again: `DISTRO=spaetzle[-flavour]` together with `tq-image-small[-debug]` is intended as example starting point for tiny systems. Please use `DISTRO=dumpling[-wayland][-flavour]` to build featured systems with `tq-image-generic[-debug]` / 
 `tq-image-weston[-debug]` / `tq-image- qt5[-debug]` with `openssh`.

**Comment by pfostenberg** [comment]
now I got it. 
If I want to use openssh install in rootfs.
neither use spaetzle OR  tq-image-small (or any other x-x-small) 

thanx.

**Comment by vi-andreas42** [comment]
can be closed. thanx.
